### ISSUE TITLE
del_history 관련 내용

### ISSUE THREAD

**Issue by Eunwoo-Lee** [heypaprika/calculator#1]
현재 보고있는 history 삭제
    def del_history(self):
        self._history_list.pop(self._cur_idx)
        self._cur_idx += 1
        return self.show_history(self._cur_idx)

1. 함수가 하는 역할을 명확하게 하는게 좋을 것 같음. 삭제 기능만 수행하면 될 것 같은데 show_history를 호출하고 있는데, 혹시 특별한 이유가 있는건지?
2. 현재 보고 있는 히스토리를 삭제하는 것 보다는 인자로 index를 받아서 해당 히스토리를 삭제하는 방법이 일반적임
3. cur_idx를 1 증가하고 난 후에 현재 히스토리의 길이를 넘어가는 것은 아닌지 확인을 해 보는 것이 좋음 (이 부분은 1번과 2번을 처리한다고 하더라도 필요할 것 같음)

**Comment by treejw** [comment]
del_history 아래와 같이 수정하였습니다!

```
def del_history(self, idx):
    self._history_list.pop(idx)
    # 예외처리
    if idx >= 0:
        self.cur_idx = idx-len(self._history_list) if idx != len(self._history_list) else -1
    else:
        self.cur_idx = idx + 1 if idx != -1 else -1
```

---

추가로 get_result_value 함수에서도 현재 보고있는 history의 결과값을 가져오는 것인데 
이것도 index를 받아서 해당 history의 결과값을 가져오는것으로 수정하는 것이 좋을까요??

**Comment by Eunwoo-Lee** [comment]
일단 get_result_value 함수에 대해서는 다른 이슈로 올릴께. 

if idx >= 0:
    self.cur_idx = idx-len(self._history_list) if idx != len(self._history_list) else -1
else:
    self.cur_idx = idx + 1 if idx != -1 else -1

이 코드에 대한 설명을 좀 해주면 좋을 것 같애.
내 생각에 idx에 있는 히스토리를 삭제했을 경우에 cur_idx가 영향을 받는 경우만 예외 처리를 해 주면 될 것 같은데, 예를 들어 cur_idx가 3인데 2번째 히스토리를 삭제하게 되면 cur_idx가 가리키고 있는 히스토리 자체가 달라지기 때문에 cur_idx 값을 -1 해줘야 하는 경우가 발생하는거지.

**Comment by treejw** [comment]
특정 index를 받아서 history를 삭제하려면 해당 index로 이동하고나서 그 history를 삭제해야 된다고 생각했습니다. 
따라서 `self.cur_idx` 가 받은 `idx` 가 되고, 받은 `idx` 가 음수인지 양수인지에 따라 `self.cur_idx`를 update 하도록 했습니다.
그리고 현재 init 함수에서 `self.cur_idx` 가 -1로 초기화되어있고,
`move_prev_history` 와 `move_next_history` 에서  `self.cur_idx` 가 계속 음수에서 움직이고 있기 때문에 history를 삭제한 후 update되는 `self.cur_idx` 가 음수로 나오도록 했습니다.

---

```
if idx >= 0:
        self.cur_idx = idx-len(self._history_list) if idx != len(self._history_list) else -1
```
이 부분은 받은 `idx` 값이 양수일 때, 이 값이 `len(self._history_list)` 즉, 마지막 history 를 가리키는게 아니라면, `self.cur_idx` 가 삭제한 history의 다음 history 를 가리키도록 음수의 index로 update 하고,
삭제한 history가 마지막 index의 history라면,
삭제한 history의 이전 history 가 마지막 index의 history가 되고,
`self.cur_idx` 가 마지막 index의 history를 가리키도록 -1 로 update 합니다. 

```
else:
    self.cur_idx = idx + 1 if idx != -1 else -1
```
이 부분은 받은 `idx` 값이 음수일 때, 마찬가지로 마지막 history 를 가리키는게 아니라면,
`self.cur_idx` 가 삭제한 history의 다음 history 를 가리키도록 음수의 index로 update 하고,
삭제한 history가 마지막 index의 history라면,
`self.cur_idx` 가 마지막 index의 history를 가리키도록 -1 로 update 합니다.

**Comment by Eunwoo-Lee** [comment]
음...현재 인덱스가 음수인 경우도 고려를 하고 있기 때문에 좀 복잡해 지는 거 같기는 하네.
차라리 move_next_history, move_prev_history에서도 음수를 허용하지 않도록 하고 del_history를 아래와 같이 구현을 하는건 어떨까? 초기화도 -1이 아닌 0으로 하고.

```
def del_history(self, idx):
    if idx < 0 or idx >= len(self._history_list):
        return
    self._history_list.pop(idx)
    if idx <= self._cur_idx:
        self._cur_idx -= 1
```

이 외에도 예외 상황이 있을지는 지원이가 알려줘야 할 것 같고.. ^^

**Comment by treejw** [comment]
아래와 같이 수정했습니당!

* del_history 함수 수정
>###### idx 가 유효할 경우 실행하도록 수정
<pre><code>    def del_history(self, idx):
        if idx < 0 or idx >= len(self.__history_list):
            error_msg = 'IndexError'
            return error_msg
        del self.__history_list[idx]
        if idx <= self.cur_idx:
            self.cur_idx -= 1
</code></pre>

* reset_history 함수 수정
>###### cur_idx를 0으로 초기화
<pre><code>    def reset_history(self):
        self.__history_list = []
        self.cur_idx = 0
</code></pre>

**Comment by Eunwoo-Lee** [comment]
수정을 잘 해줬는데 실제 코드는 아래처럼 되어 있네

```
    def del_history(self, idx):
        if 0 < idx <= len(self.__history_list):
            del self.__history_list[idx]
            if idx <= self.cur_idx:
                self.cur_idx -= 1
        else:
            print('IndexError')
```

위 경우라면 idx가 0일 경우에는 삭제가 안될것 같애.
그리고 가장 마지막 history를 삭제하고 난 이후의 상황도 확인을 해봐야 할 것 같은데, 이건 나도 명확하지 않아서 잘 모르겠네.

**Comment by treejw** [comment]
최신버전으로 안올렸네요.. 다시 올렸습니다!!
