### ISSUE TITLE
reset_history

### ISSUE THREAD

**Issue by Eunwoo-Lee** [heypaprika/calculator#2]
# history_list 초기화
    def reset_history(self):
        self._history_list = []

리스트는 초기화하고 있지만 cur_idx는 초기화 되고 있지 않고 있음

def __init__(self):
        self._history_list = []
        self._cur_idx = -1

차라리 init함수 내용을 reset_history로 옮기고 init에서는 reset_history를 호출하는 것은 어떨지...

**Comment by treejw** [comment]
아래와 같이 수정 완료했습니다!

* reset_history 
```
def reset_history(self):
        self._history_list = []
        self.cur_idx = -1
```

* init
```
def __init__(self):
    self.reset_history()
```

**Comment by Eunwoo-Lee** [comment]
Good Job
