### ISSUE TITLE
get_result_value

### ISSUE THREAD

**Issue by Eunwoo-Lee** [heypaprika/calculator#3]
현재 보고있는 history의 결과값 가져오기
def get_result_value(self):
    result_value = self._history_list[self.cur_idx].split('=')[-1]
    return result_value

이 함수의 역할은 현재 히스토리의 계산 결과 값을 가져오는 것인데, 이 함수는 계산기라는 어플리케이션에만 필요한 함수인 것 같애.
history_controller에서는 단순하게 get_history(self, idx)라는 함수만 만들고, 만약 계산된 결과 값을 얻어가야 한다면 그건 계산기 앱에서 구현하는게 맞을 것 같은데..어떻게 생각해?

**Comment by treejw** [comment]
저도 나중에 calculator class를 만들때 get_result_value 함수를 추가 하는게 좋을것 같습니당!
그리고 기존의 show_history(self, idx=-1) 라는 함수가 말씀하신 get_history(self, idx) 함수의 역할을 하고 있는 것 같아서 위의 2개 함수를 아래와 같이 수정할 계획입니다..!


* 기존 코드
```
# 현재 보고있는 history의 결과값 가져오기
def get_result_value(self):
    result_value = self._history_list[self.cur_idx].split('=')[-1]
    return result_value
```

```
# index 받아서 해당 history 리턴
# index 안넣어줄 경우 가장 최근에 저장된 history 리턴
def show_history(self, idx=-1):
    if len(self._history_list) == 0:
        return ''
    return self._history_list[idx]
```

* 수정계획

```
# 현재 저장된 모든 history를 리스트로 리턴
# 리스트의 마지막 index가 가장 최근에 저장된 history
def get_all_history(self):
    return self._history_list
```

```
# index 받아서 해당 history 리턴
# index 안넣어줄 경우 가장 최근에 저장된 history 리턴
def get_history(self, idx=-1):
    if len(self._history_list) == 0:
        return ''
    return self._history_list[idx]
```

**Comment by Eunwoo-Lee** [comment]
기본적으로 수정계획은 좋은거 같애.

근데 파이썬에서는 리스트의 인덱스를 확인하지 않아도 되는건가?
예를 들어 입력된 인덱스가 len보다 크면 어떤 값이 리턴되는건지 모르겠네.

명시적으로 idx가 len보다 작을 경우에도 ' '를 리턴하도록 해주는게 좋지 않을까 싶어서 물어본거야.

**Comment by treejw** [comment]
이번에 전체적으로 다시 수정해서 올렸습니당!
* HISTORY 클래스 추가
<pre><code>class HISTORY:
    def __init__(self, h):
        if type(h) != str: h = str(h)
        self.h = h

    def __len__(self):
        return len(self.h)

    def get_history_str(self):
        return str(self.h)

    def get_ans_str(self):
        return self.h.split('=')[-1].strip()

    def get_ans_float(self):
        return float(self.h.split('=')[-1])</code></pre>
> ###### 이에따른 history_controller 클래스의 save_history 부분 수정
<pre><code>    def save_history(self, history):
        self.__history_list.insert(0, HISTORY(history))
</pre></code>

* index 고려한 부분 추가.
> ###### index가 list 길이보다 크면 오류메세지 출력.
<pre><code>    def get_history(self, idx=0):
        if len(self.__history_list) == 0:
            return ''
        elif idx >= len(self.__history_list):
            print('IndexError')
            return ''
        return self.__history_list[idx].get_history_str()
</code></pre>

**Comment by Eunwoo-Lee** [comment]
수정 잘 했네. 수고했어. ㅎㅎ
